name: Production build on Expo with EAS
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build with EAS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: 2.7.0
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install Dependencies
        run: yarn --prefer-offline

      - name: Production build on EAS
        run: yarn build
