name: Unit testing on PRs

on:
  pull_request:
    branches:
      - main
jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn --prefer-offline

      - name: Run tests
        run: yarn test --coverage
